services:
  minecraft-vanilla:
    image: itzg/minecraft-server
    container_name: minecraft-vanilla
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - /srv/gameservers/minecraft-vanilla/data:/data
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - VERSION=LATEST
      - MEMORY=8G
      - OPS=Marshixel
      - WHITELIST=Marshixel
      - ENFORCE_WHITELIST=TRUE
      - MOTD=Marshixel Homelab Server
      - DIFFICULTY=hard
      - MAX_PLAYERS=10
